version: '3.8'

services:
  sf6-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sf6framedata
      - SPRING_DATASOURCE_USERNAME=sf6user
      - SPRING_DATASOURCE_PASSWORD=framedata123
    depends_on:
      - postgres
    networks:
      - sf6-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sf6framedata
      - POSTGRES_USER=sf6user
      - POSTGRES_PASSWORD=framedata123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - sf6-network

volumes:
  postgres_data:

networks:
  sf6-network:
    driver: bridge
