version: '3.8'

services:
  sf6-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - fg-framedata-api_pgdata:/var/lib/postgresql/data
    networks:
      - sf6-network

  sf6-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - sf6-db
    networks:
      - sf6-network

networks:
  sf6-network:

volumes:
  fg-framedata-api_pgdata:
