server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sf6
    username: sf6user
    password: sf6pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
